version: '3'

services:
  osrm-data:
    image: irony/osrm5
    volumes:
      - /data
  osrm:
    image: irony/osrm5
    volumes:
      - /data
    environment:
      - VIRTUAL_HOST=kzroutes.pstuffapp.com
      - LETSENCRYPT_HOST=kzroutes.pstuffapp.com
      - LETSENCRYPT_EMAIL=absorber000@gmail.com
    command: ./start.sh kazakstan https://download.geofabrik.de/asia/kazakhstan-latest.osm.pbf
    networks:
      - default

networks:
  default:
    external:
      name: nginxproxy_proxy
