version: '2'

services:
  osrm-data:
    image: irony/osrm5
    volumes:
      - /data
  osrm:
    image: irony/osrm5
    volumes_from:
      - osrm-data
    ports:
      - "5000:5000"
    command: ./start.sh central-fed-district https://download.geofabrik.de/russia/central-fed-district-latest.osm.pbf // имя должно совпадать с именем файла без '-latest'
