version: '2'

services:
  osrm-data:
    image: irony/osrm5
    volumes:
      - /data
  osrm:
    image: irony/osrm5
    volumes_from:
      - osrm-data
    ports:
      - "5000:5000"
    command: ./start.sh kazakstan https://download.geofabrik.de/asia/kazakhstan-latest.osm.pbf
